### ISSUE TITLE
Check Wine Reviews Dataset

### ISSUE THREAD

**Issue by ka3nt** [dilara444/TechLabsDUS_WineNot#7]
We need to decide if we want to have additional research on wine reviews in different regions

**Comment by dilara444** [comment]
We will use this data set seperately. 
The review will be contributing to the global quality estimation or somehow just to show which wines are most preferred globally and produced with what characteristic taste.

**Comment by dilara444** [comment]
This dataset was selected as the main source for our analysis. We will use EDA to work with this dataset. Various approaches will be implemented to demonstrate the connections and outstanding characteristics for some wine types.
